agenda/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView
from django.contrib.auth.decorators import login_required
from core import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", login_required(TemplateView.as_view(template_name="index.html")), name="index"),
    path("accounts/login/", views.login, name="login"),
    path("logout/", views.logout, name="logout"),
    path("accounts/login/submit", views.submit_login, name="submit_login"),
    path("user/", include("client.urls")),
]

client/urls.py
from django.urls import path
from .views import UserCreateView, TaskCreateView, TaskReadView, TaskUpdateView, TaskDeleteView
from django.contrib.auth.decorators import login_required

app_name = "tasks"

urlpatterns = [
    path("user/create/", UserCreateView.as_view(), name="user-create"),
    path("user/<int:user_id>/task/create/", login_required(TaskCreateView.as_view()), name="task-create"),
    path("user/<int:user_id>/task/<int:task_id>/", login_required(TaskUpdateView.as_view()), name="task-update"),
    path("user/<int:user_id>/task/delete/<int:task_id>/", login_required(TaskDeleteView.as_view()), name="task-delete"),
    path("user/<int:user_id>/task/list/", login_required(TaskReadView.as_view()), name="task-list")
]

core/models.py
from django.db import models

# Create your models here.

client/views.py
from django.shortcuts import redirect, render
from django.views.generic import CreateView, ListView, UpdateView, DeleteView
from .forms_user import UserForm
from .forms_tasks import TaskForm
from django.urls import reverse_lazy, reverse
from django.contrib.auth.models import User
from .models_user import UserProfile
from django.contrib import messages
from django.db.models import Q
from .model_tasks import Tasks
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import get_object_or_404


class UserCreateView(CreateView):
    template_name = "client/user.html"
    form_class = UserForm
    success_url = reverse_lazy("tasks:user-create")

    def form_valid(self, form):

        first_name = form.cleaned_data["first_name"]
        last_name = form.cleaned_data["last_name"]
        birth_date = form.cleaned_data['birth_date']
        email = form.cleaned_data['email']
        username = form.cleaned_data['username']
        password = form.cleaned_data['password1']

        user = User.objects.create_user(username=username, password=password)
        user.first_name = first_name
        user.last_name = last_name
        user.save()

        UserProfile.objects.create(user=user, first_name=first_name, last_name=last_name, birth_date=birth_date,
                                   email=email)

        return redirect("index")


class TaskCreateView(CreateView):
    template_name = "client/task.html"
    form_class = TaskForm
    success_url = reverse_lazy("tasks:task-create")

    def form_valid(self, form):
        try:
            task = form.save(commit=False)
            task.user_id = User.objects.get(id=self.request.user.id)
        except Exception:
            messages.error("Error to save your task.")
            print(Exception)
        else:
            task.save()
        return redirect("index")


class TaskReadView(LoginRequiredMixin, ListView):
    template_name = "client/task_list.html"
    paginate_by = 10
    model = Tasks

    def get_queryset(self):
        title = self.request.GET.get('title')
        user = self.request.user
        if title:
            object_list = self.model.objects.filter(
                Q(title__icontains=title) | Q(tags__icontains=title), user_id=user
            )
        else:
            object_list = self.model.objects.filter(user_id=user)
        return object_list.order_by('date_creation_task')


class TaskUpdateView(UpdateView):
    template_name = "client/task.html"
    model = Tasks
    form_class = TaskForm
    success_url = reverse_lazy("tasks:task-create")

    def get_object(self):
        task_id = self.kwargs.get("task_id")
        user_id = self.kwargs.get("user_id")
        return get_object_or_404(Tasks, user_id=user_id, id=task_id)

    def form_valid(self, form):
        try:
            task = form.save(commit=False)
            task.user_id = User.objects.get(id=self.request.user.id)
        except Exception:
            messages.error("Error to save your task.")
            print(Exception)
        else:
            task.save()
        return redirect("index")


class TaskDeleteView(DeleteView):
    model = Tasks
    template_name = "tasks:task-list"

    def get_object(self):
        task_id = self.kwargs.get("task_id")
        user_id = self.kwargs.get("user_id")
        return get_object_or_404(Tasks, user_id=user_id, id=task_id)

    def get_success_url(self):
        user_id = self.kwargs.get("user_id")
        return reverse_lazy("tasks:task-list", kwargs={"user_id": user_id})

core/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login as app_login, logout as app_logout
from django.contrib import messages


def login(request):
    return render(request, "login.html")


def submit_login(request):
    if request.POST:
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username=username, password=password)
        if user is not None:
            app_login(request, user)
            return redirect("index")
        else:
            messages.error(request, "User or password invalid. Please, try again!")
    else:
        if not request.user.is_authenticated:
            return redirect("user-create")
    return redirect("index")


def logout(request):
    app_logout(request)
    return redirect("login")


def check_login(request):
    if request.user.is_authenticated:
        return redirect("index")
    else:
        return redirect("login")

client/templates/client/task.html
{% extends "model-page.html" %}
{% load crispy_forms_tags %}
{% block content %}
    {% if form.errors %}
        {% for field in form %}
            {% for error in field.errors %}
                <div class="alert alert-danger">
                    <strong>{{ error|escape }}</strong>
                </div>
            {% endfor %}
        {% endfor %}
    {% endif %}

    <form method="POST">
      {% csrf_token %}
        {{ form|crispy }}
        <button type="submit" class="btn btn-primary">Save</button>
    </form>
{% endblock %}

client/templates/client/task_list.html
{% extends "model-page.html" %}

{% block content %}

  <h2>Tasks</h2>

  <form>
    <div class="form-group mt-1">
      <input class="form-control" type="text" name="title" placeholder="Search by tag or title...">
    </div>
    <button type="submit" class="btn btn-primary">Search</button>
  </form>

  <a href="{% url 'tasks:task-create' user_id=request.user.id %}">
    <button type="button" class="btn btn-success"
            style="float: right; margin-botton: 5px">Add</button>
  </a>

  <table class="table table-bordered mt-4">
    <thead>
      <tr>
        <th>Title</th>
        <th>Tag</th>
        <th>Description</th>
        <th>Date</th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      {% for task in page_obj %}
        <tr>
          <td><a href="{% url 'tasks:task-update' user_id=user.id task_id=task.id %}">{{ task.title }}</a></td>
          <td>{{ task.tags }}</td>
          <td>{{ task.description }}</td>
          <td>{{ task.task_date }}</td>
          <form method="post" action="{% url 'tasks:task-delete' user_id=user.id task_id=task.id %}">{% csrf_token %}
            <td><button type="submit" class="btn btn-danger">Delete</button></td>
          </form>
        </tr>
      {% endfor %}
    </tbody>
  </table>

  <ul class="pagination">
    {% if page_obj.has_previous %}
      <li class="page-item"><a class="page-link" href="?page={{ page_obj.previous_page_number }}">Previous</a></li>
    {% else %}
      <li class="page-item disabled"><a class="page-link" href="#">Previous</a></li>
    {% endif %}
    {% for object in page_obj.paginator.page_range %}
      <li class="page-item"><a class="page-link" href="?page={{ forloop.counter }}">{{ forloop.counter }}</a></li>
    {% endfor %}
      {% if page_obj.has_next %}
      <li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}">Next</a></li>
    {% else %}
      <li class="page-item disabled"><a class="page-link" href="#">Next</a></li>
    {% endif %}

  </ul>

{% endblock %}

client/templates/client/user.html
{% extends "model-page.html" %}
{% load crispy_forms_tags %}
{% block content %}
    {% if form.errors %}
        {% for field in form %}
            {% for error in field.errors %}
                <div class="alert alert-danger">
                    <strong>{{ error|escape }}</strong>
                </div>
            {% endfor %}
        {% endfor %}
    {% endif %}

    <form method="POST">
      {% csrf_token %}
        {{ form|crispy }}
        <button type="submit" class="btn btn-primary">Save</button>
    </form>
{% endblock %}

core/templates/index.html
{% extends "model-page.html" %}

{% block content %}
    <ul class="navbar-nav mr-auto">
        <li class="nav-item">
            <a class="nav-link" href="{% url 'tasks:task-list' user_id=request.user.id %}">See Tasks</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{% url 'tasks:task-create' user_id=request.user.id %}">Create Task</a>
        </li>
    </ul>
{% endblock %}

core/templates/login.html
{% load static %}

<html lang="pt-br">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script>
    <link rel="stylesheet" href="{% static 'css/login.css' %}">


</head>

<body class="d-flex flex-column">
  <div class="sidenav">
         <div class="login-main-text">
            <h2>Tasks Manager App<br></h2>
         </div>
      </div>
      <div class="main">
         <div class="col-md-6 col-sm-12">
            <div class="login-form">
               <form action="submit", method="POST">
                {% csrf_token %}
                  <div class="form-group">
                     <label>User</label>
                     <input type="text" class="form-control" placeholder="User" name="username">
                  </div>
                  <div class="form-group">
                     <label>Password</label>
                     <input type="password" class="form-control" placeholder="Password" name="password">
                  </div>
                  {% if messages %}
                      {% for message in messages %}
                          <div class="alert alert-danger">{{ message }}</div>
                      {% endfor %}

                  {% endif %}
                  <button type="submit" class="btn btn-success">Login</button>
                  <button type="button" class="btn btn-outline-primary">
                      <a href="{% url 'tasks:user-create' %}">Create Account</a></button>
               </form>
            </div>
         </div>
      </div>
</body>
</html>

core/templates/model-footer.html
<div class="container text-center">
    <small>Developed by Henrique Gonzaga</small>
</div>

core/templates/model-header.html
<nav class="navbar navbar-expand-sm bg-dark navbar-dark">
    {% if user.is_authenticated %}
        <a class="navbar-brand" href="{% url 'index' %}">Home Page</a>
    {% else %}
        <a class="navbar-brand" href="{% url 'logout' %}">Home Page</a>
    {% endif %}
    <a class="" href="{% url 'logout' %}">Logout</a>

</nav>

core/templates/model-page.html
<!DOCTYPE html>
{% load crispy_forms_tags %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
  <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.7/dist/umd/popper.min.js" integrity="sha384-zYPOMqeu1DAVkHiLqWBUTcbYfZ8osu1Nd6Z89ify25QV9guujx43ITvfi12/QExE" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.min.js" integrity="sha384-Y4oOpwW3duJdCWv5ly8SCFYWqFDsfob/3GkgExXKV4idmbt98QcxXYs9UoXAB7BZ" crossorigin="anonymous"></script>
</head>
<body class="d-flex flex-column">
  <header>
    {% include "model-header.html" %}
  </header>

  <main class="content" style="margin-top: 5%">
    <div class="container">
    {% block content %} {% endblock %}
    </div>
  </main>

  <footer class="py-4 bg-dark text-white-50">
    {% include "model-footer.html" %}
  </footer>

</body>

<style>
  html, body{
    height: 100%;
  }
  main{
    flex: 1 0 auto;
  }
  footer{
    flex-shrink: none;
    margin-top: 2em;
  }
</style>

</html>